import Head from 'next/head'
import { Flex } from '@/components/Base/Div'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>Hello world</Flex>
    </div>
  )
}
